# Generated by Django 4.2.5 on 2024-01-06 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
            ],
            options={
                'verbose_name': '分类信息',
                'verbose_name_plural': '分类信息',
                'db_table': 'db_category',
            },
        ),
        migrations.CreateModel(
            name='FoodModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('image', models.ImageField(max_length=300, upload_to='', verbose_name='图片')),
                ('price', models.IntegerField(default=100, verbose_name='价格')),
                ('number', models.IntegerField(default=0, verbose_name='数量')),
                ('content', models.TextField(verbose_name='介绍')),
                ('view_count', models.IntegerField(default=0, verbose_name='浏览量')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info_manage.categorymodel', verbose_name='所属分类')),
            ],
            options={
                'verbose_name': '食物信息',
                'verbose_name_plural': '食物信息',
                'db_table': 'db_food',
            },
        ),
        migrations.CreateModel(
            name='UserInfoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, verbose_name='用户名')),
                ('password', models.CharField(max_length=100, verbose_name='密码')),
                ('address', models.CharField(max_length=100, verbose_name='地址')),
                ('phone', models.CharField(max_length=100, verbose_name='手机号')),
                ('money', models.IntegerField(verbose_name='余额')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='加入时间')),
            ],
            options={
                'verbose_name': '用户信息',
                'verbose_name_plural': '用户信息',
                'db_table': 'db_user_info',
            },
        ),
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(verbose_name='总价格')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info_manage.foodmodel', verbose_name='所属食物')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info_manage.userinfomodel', verbose_name='所属用户')),
            ],
            options={
                'verbose_name': '订单信息',
                'verbose_name_plural': '订单信息',
                'db_table': 'db_order',
            },
        ),
        migrations.CreateModel(
            name='MarkModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=5, verbose_name='评分')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info_manage.foodmodel', verbose_name='所属食物')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info_manage.userinfomodel', verbose_name='所属用户')),
            ],
            options={
                'verbose_name': '评分信息',
                'verbose_name_plural': '评分信息',
                'db_table': 'db_mark',
            },
        ),
        migrations.CreateModel(
            name='LikeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info_manage.foodmodel', verbose_name='所属食物')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info_manage.userinfomodel', verbose_name='所属用户')),
            ],
            options={
                'verbose_name': '用户收藏',
                'verbose_name_plural': '用户收藏',
                'db_table': 'db_like',
            },
        ),
        migrations.CreateModel(
            name='HotModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info_manage.foodmodel', verbose_name='热门食物')),
            ],
            options={
                'verbose_name': '热门食物',
                'verbose_name_plural': '热门食物',
                'db_table': 'db_hot',
            },
        ),
        migrations.CreateModel(
            name='CommentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='评论内容')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info_manage.foodmodel', verbose_name='所属食物')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info_manage.userinfomodel', verbose_name='所属用户')),
            ],
            options={
                'verbose_name': '评论信息',
                'verbose_name_plural': '评论信息',
                'db_table': 'db_comment',
            },
        ),
    ]
